/**
 * Your application code goes here<br>
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */


package userclasses;

import generated.StateMachineBase;
import com.codename1.ui.*; 
import com.codename1.ui.events.*;
import com.codename1.ui.util.Resources;

/**
 *
 * @author Your name here
 */
public class StateMachine extends StateMachineBase {
    public StateMachine(String resFile) {
        super(resFile);
        // do not modify, write code in initVars and initialize class members there,
        // the constructor might be invoked too late due to race conditions that might occur
    }
    
    /**
     * this method should be used to initialize variables instead of
     * the constructor/class scope to avoid race conditions
     */
    protected void initVars(Resources res) {
    }

    @Override
    protected void onNewProject_NewProjectDateOfTestingAddButtonAction(Component c, ActionEvent event) {
        Dialog d = (Dialog) createContainer(fetchResourceFile(), "dateOftestingDialog");
        Button saveButton = (Button) findByName("dateOfTestingSaveButton", d);
        saveButton.addActionListener(evt -> {
            Dialog.show("Greetings", "DateOfTesting", "OK", null);
            d.dispose();
        });
        Button cancelButton = (Button) findByName("dateOfTestingCancelButton",d);
        cancelButton.addActionListener(evt -> {
            d.dispose();
        });
        d.show();
    }

    @Override
    protected void onNewProject_NewProjectSubmittedToAddButtonAction(Component c, ActionEvent event) {
        Dialog d = (Dialog) createContainer(fetchResourceFile(), "newUserEntry");
        Button saveButton = (Button) findByName("newUserEntrySaveButton", d);
        saveButton.addActionListener(evt -> {
            Dialog.show("Greetings", "SubmittedToAddButton", "OK", null);
            d.dispose();
        });
        Button cancelButton = (Button) findByName("newUserEntryCancelButton",d);
        cancelButton.addActionListener(evt -> {
            d.dispose();
        });
        d.show();
    }

    @Override
    protected void onNewProject_NewProjectPreparedByAddButtonAction(Component c, ActionEvent event) {
        Dialog d = (Dialog) createContainer(fetchResourceFile(), "newUserEntry");
        Button saveButton = (Button) findByName("newUserEntrySaveButton", d);
        saveButton.addActionListener(evt -> {
            Dialog.show("Greetings", "PreparedByAddButton", "OK", null);
            d.dispose();
        });
        Button cancelButton = (Button) findByName("newUserEntryCancelButton",d);
        cancelButton.addActionListener(evt -> {
            d.dispose();
        });
        d.show();
    }

    @Override
    protected void onNewProject_NewProjectInPresenceOfAddButtonAction(Component c, ActionEvent event) {
        Dialog d = (Dialog) createContainer(fetchResourceFile(), "newUserEntry");
        Button saveButton = (Button) findByName("newUserEntrySaveButton", d);
        saveButton.addActionListener(evt -> {
            Dialog.show("Greetings", "InPresenceOf", "OK", null);
            d.dispose();
        });
        Button cancelButton = (Button) findByName("newUserEntryCancelButton",d);
        cancelButton.addActionListener(evt -> {
            d.dispose();
        });
        d.show();
    }
}
